version: '3.4'

services:
  playerbot:
    build: .  
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - MYSQL_HOST=localhost
      - MYSQL_USER=mangos
      - MYSQL_PASS=mangos