version: "3.8"

services:
  tbc:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "8085:8085"
      - "3724:3724"
    volumes:
      - ./mangosd/etc:/mangos/etc
      - ./mangosd/backup:/mangos/backup
      - ./mangosd/logs:/mangos/logs
  playerbot-api:
    build: src/playerbot/api/
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - MYSQL_HOST=db
      - MYSQL_USER=mangos
      - MYSQL_PASS=limewire14
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./rw:/mosquitto/:rw
      - ./mosquitto/config/:/mosquitto/config/
    ports:
      - 1883:1883
      - 9001:9001
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: limewire14
    volumes:
      - ./mysql:/var/lib/mysql
