version: "3"

services:
  api:
    build: api/
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - MYSQL_HOST=192.168.1.209
      - MYSQL_USER=mangos
      - MYSQL_PASS=limewire14
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./rw:/mosquitto/:rw
      - ./mosquitto/config/:/mosquitto/config/
    ports:
      - 1883:1883
      - 9001:9001