version: "3"

services:
  api:
    build: api/
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - MYSQL_HOST=db
      - MYSQL_USER=mangos
      - MYSQL_PASS=limewire14
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./rw:/mosquitto/:rw
      - ./mosquitto/config/:/mosquitto/config/
    ports:
      - 1883:1883
      - 9001:9001
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: limewire14
    volumes:
      - ./mysql:/var/lib/mysql
